name = "driver-fatigue-backend"
main = "src/index.ts"
compatibility_date = "2026-09-17"

[[d1_databases]]
binding = "DB"
database_name = "driver-fatigue-db"
database_id = "d4fcdbb4-2c69-4ec1-afea-f95015ea22b1"
migrations_dir = "migrations"

[ai]
binding = "AI"
remote = true