import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Header, PrimaryButton } from '../components/ui';
import type { FatigueEngine } from '@/features/fatigue/engine';
import { useFatigueState } from '@/features/fatigue/use-fatigue-state';
import { colors } from '../theme';
type Phase = 'eye' | 'head' | 'complete';
// This calibration flow intentionally resets its countdown whenever the phase changes.
// eslint-disable-next-line react-hooks/set-state-in-effect
export function CalibrationScreen({ engine, onBack, onComplete }: { engine: FatigueEngine; onBack: () => void; onComplete: () => void }) { const [phase, setPhase] = useState<Phase>('eye'), [elapsed, setElapsed] = useState(0); const { calibration } = useFatigueState(engine); useEffect(() => { engine.startCalibration(); }, [engine]); useEffect(() => { if (phase === 'complete') return; setElapsed(0); const timer = setInterval(() => setElapsed((value) => { if (value >= 4900) { clearInterval(timer); setPhase('head'); return 5000; } return value + 100; }), 100); return () => clearInterval(timer); }, [phase]); const progress = Math.min(elapsed / 5000, 1), countdown = Math.max(0, Math.ceil((5000 - elapsed) / 1000)); const shown: Phase = calibration === 'done' ? 'complete' : phase; const retry = () => { engine.startCalibration(); setPhase('eye'); }; const status = calibration === 'failed' ? 'Нүүр тогтвортой харагдсангүй' : shown === 'eye' ? 'Нүдний хэвийн төлөвийг тодорхойлж байна' : shown === 'head' ? 'Толгойн хэвийн байрлалыг тодорхойлж байна' : 'Калибраци амжилттай дууслаа!'; return <View style={styles.screen}><Header title="Калибраци" onBack={onBack} badge="2 / 2" /><View style={styles.center}>{shown === 'complete' ? <View style={styles.successCircle}><Text style={styles.successIcon}>✓</Text></View> : <View style={styles.progressCircle}><Text style={styles.phaseIcon}>{shown === 'eye' ? '◉' : '☺'}</Text><Text style={styles.countdown}>{countdown}</Text><View style={styles.track}><View style={[styles.fill, { width: `${progress * 100}%` }]} /></View></View>}<Text style={styles.status}>{status}</Text><Text style={styles.hint}>{shown === 'eye' ? 'Урагшаа харж, нүдээ хэвийн анивчина уу' : shown === 'head' ? 'Толгойгоо эгц, хөдөлгөөнгүй байлгана уу' : 'Систем таны хэвийн төлөвийг саналаа'}</Text><View style={styles.steps}><Step label="Нүд" done={shown !== 'eye'} active={shown === 'eye'} /><View style={styles.line} /><Step label="Толгой" done={shown === 'complete'} active={shown === 'head'} /></View>{shown === 'complete' ? <View style={styles.button}><PrimaryButton label="Жолоодлого эхлүүлэх" onPress={onComplete} /></View> : null}{calibration === 'failed' ? <View style={styles.button}><PrimaryButton label="Дахин калибраци хийх" onPress={retry} /></View> : null}</View></View>; }
function Step({ label, done, active }: { label: string; done: boolean; active: boolean }) { return <View style={styles.step}><View style={[styles.stepDot, (done || active) && styles.stepDotActive]}><Text style={styles.stepText}>{done ? '✓' : '•'}</Text></View><Text style={[styles.stepLabel, active && styles.stepLabelActive]}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 }, progressCircle: { width: 190, height: 190, borderRadius: 95, borderColor: colors.primary, borderWidth: 3, alignItems: 'center', justifyContent: 'center', backgroundColor: '#101A2D' }, successCircle: { width: 170, height: 170, borderRadius: 85, backgroundColor: colors.normalDark, borderColor: colors.normal, borderWidth: 2, alignItems: 'center', justifyContent: 'center' }, successIcon: { color: colors.normal, fontSize: 72, fontWeight: '700' }, phaseIcon: { color: colors.primary, fontSize: 42 }, countdown: { color: colors.text, fontSize: 30, fontWeight: '800', marginTop: 4 }, track: { position: 'absolute', bottom: 22, left: 28, right: 28, height: 5, borderRadius: 3, backgroundColor: colors.borderBright, overflow: 'hidden' }, fill: { height: '100%', backgroundColor: colors.primary }, status: { color: colors.text, fontSize: 18, fontWeight: '700', textAlign: 'center', marginTop: 32 }, hint: { color: colors.textMuted, textAlign: 'center', lineHeight: 20, marginTop: 8 }, steps: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 34 }, step: { alignItems: 'center', width: 76 }, stepDot: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.surfaceAlt, alignItems: 'center', justifyContent: 'center' }, stepDotActive: { backgroundColor: colors.primary }, stepText: { color: colors.white, fontWeight: '800' }, stepLabel: { color: colors.textMuted, fontSize: 12, marginTop: 7 }, stepLabelActive: { color: colors.text }, line: { width: 64, height: 2, backgroundColor: colors.borderBright, marginTop: 16 }, button: { alignSelf: 'stretch', marginTop: 40 } });
