import { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Header } from '../components/ui';
import { colors } from '../theme';
import { getLocalSessions, type LocalSession } from '@/data/local-db';
import { TripDetailScreen } from './TripDetailScreen';
type Filter = 'all' | 'safe' | 'warning';
function formatDuration(startedAt: string, endedAt: string | null) { const seconds = endedAt ? Math.max(0, Math.round((Date.parse(endedAt) - Date.parse(startedAt)) / 1000)) : 0; return seconds >= 3600 ? `${Math.floor(seconds / 3600)} ц ${Math.floor((seconds % 3600) / 60)} мин` : `${Math.floor(seconds / 60)} мин`; }
function toHistoryItem(session: LocalSession) { const started = new Date(session.started_at); const ended = session.ended_at ? new Date(session.ended_at) : null; return { date: `${started.getMonth() + 1}-р сарын ${started.getDate()}`, time: `${started.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} – ${ended ? ended.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'үргэлжилж байна'}${typeof session.distance_km === 'number' ? ` · ${session.distance_km} км` : ''}`, duration: formatDuration(session.started_at, session.ended_at), max: Math.round(session.fatigue_score), avg: typeof session.avg_score === 'number' ? String(Math.round(session.avg_score)) : '—', warnings: session.warning_count, critical: session.critical_event_count, online: Boolean(session.synced_at) }; }
export function HistoryScreen() { const [filter, setFilter] = useState<Filter>('all'); const [sessions, setSessions] = useState<LocalSession[]>([]); const [selected, setSelected] = useState<LocalSession | null>(null); const closeDetail = useCallback(() => setSelected(null), []); useEffect(() => { void getLocalSessions().then(setSessions).catch((error) => console.warn('Unable to load local history:', error)); }, []); const visible = sessions.map((session) => ({ session, item: toHistoryItem(session) })).filter(({ item }) => filter === 'all' || (filter === 'safe' ? item.max < 40 : item.max >= 40)); if (selected) return <TripDetailScreen session={selected} onBack={closeDetail} />; return <View style={styles.screen}><Header title="Жолоодлогын түүх" subtitle="Өнгөрсөн сессүүд" badge="Орон нутаг" /><View style={styles.filters}>{([['all', 'Бүгд'], ['safe', 'Аюулгүй'], ['warning', 'Анхаарсан']] as const).map(([key, label]) => <Pressable key={key} onPress={() => setFilter(key)} style={[styles.filter, filter === key && styles.filterActive]}><Text style={[styles.filterText, filter === key && styles.filterTextActive]}>{label}</Text></Pressable>)}</View><ScrollView contentContainerStyle={styles.content}>{visible.map(({ session, item }) => <Pressable key={session.client_id} accessibilityRole="button" onPress={() => setSelected(session)}><Card style={styles.card}><View style={styles.cardHeader}><View><Text style={styles.date}>{item.date}</Text><Text style={styles.time}>{item.time}</Text></View><Text style={[styles.score, { color: item.max >= 70 ? colors.critical : item.max >= 40 ? colors.warning : colors.normal }]}>{item.max}</Text></View><View style={styles.divider} /><View style={styles.metrics}><Metric label="Хугацаа" value={item.duration} /><Metric label="Дундаж" value={item.avg} /><Metric label="Анхааруулга" value={String(item.warnings)} /><Metric label="Аюултай" value={String(item.critical)} /></View><View style={styles.footer}><Text style={[styles.online, { color: item.online ? colors.normal : colors.textMuted }]}>{item.online ? '● Серверт илгээгдсэн' : '○ Офлайн хадгалсан'}</Text><Text style={styles.more}>Дэлгэрэнгүй ›</Text></View></Card></Pressable>)}</ScrollView></View>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, filters: { flexDirection: 'row', gap: 8, paddingHorizontal: 20, marginBottom: 12 }, filter: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18, backgroundColor: colors.surfaceAlt }, filterActive: { backgroundColor: colors.primary }, filterText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' }, filterTextActive: { color: colors.white }, content: { paddingHorizontal: 20, paddingBottom: 110 }, card: { marginBottom: 12 }, cardHeader: { flexDirection: 'row', justifyContent: 'space-between' }, date: { color: colors.text, fontSize: 16, fontWeight: '700' }, time: { color: colors.textMuted, fontSize: 12, marginTop: 4 }, score: { fontSize: 26, fontWeight: '800' }, divider: { height: 1, backgroundColor: colors.border, marginVertical: 14 }, metrics: { flexDirection: 'row' }, metric: { flex: 1 }, metricValue: { color: colors.text, fontSize: 14, fontWeight: '700' }, metricLabel: { color: colors.textMuted, fontSize: 9, marginTop: 3 }, online: { fontSize: 10 }, footer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 14 }, more: { color: colors.primary, fontSize: 11, fontWeight: '600' } });
