import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Header } from '../components/ui';
import { colors } from '../theme';
type Filter = 'all' | 'safe' | 'warning';
const sessions = [{ date: '9-р сарын 16', time: '18:20 – 19:05', duration: '45 мин', max: 38, avg: 24, warnings: 0, critical: 0, online: true }, { date: '9-р сарын 14', time: '08:10 – 09:22', duration: '1 ц 12 мин', max: 67, avg: 42, warnings: 2, critical: 0, online: true }, { date: '9-р сарын 11', time: '21:30 – 23:02', duration: '1 ц 32 мин', max: 84, avg: 51, warnings: 3, critical: 1, online: false }, { date: '9-р сарын 8', time: '12:05 – 12:38', duration: '33 мин', max: 31, avg: 20, warnings: 0, critical: 0, online: true }];
export function HistoryScreen() { const [filter, setFilter] = useState<Filter>('all'); const visible = sessions.filter((item) => filter === 'all' || (filter === 'safe' ? item.max < 40 : item.max >= 40)); return <View style={styles.screen}><Header title="Жолоодлогын түүх" subtitle="Өнгөрсөн сессүүд" badge="9-р сар" /><View style={styles.filters}>{([['all', 'Бүгд'], ['safe', 'Аюулгүй'], ['warning', 'Анхаарсан']] as const).map(([key, label]) => <Pressable key={key} onPress={() => setFilter(key)} style={[styles.filter, filter === key && styles.filterActive]}><Text style={[styles.filterText, filter === key && styles.filterTextActive]}>{label}</Text></Pressable>)}</View><ScrollView contentContainerStyle={styles.content}>{visible.map((item) => <Card key={`${item.date}-${item.time}`} style={styles.card}><View style={styles.cardHeader}><View><Text style={styles.date}>{item.date}</Text><Text style={styles.time}>{item.time}</Text></View><Text style={[styles.score, { color: item.max >= 70 ? colors.critical : item.max >= 40 ? colors.warning : colors.normal }]}>{item.max}</Text></View><View style={styles.divider} /><View style={styles.metrics}><Metric label="Хугацаа" value={item.duration} /><Metric label="Дундаж" value={String(item.avg)} /><Metric label="Анхааруулга" value={String(item.warnings)} /><Metric label="Аюултай" value={String(item.critical)} /></View><Text style={[styles.online, { color: item.online ? colors.normal : colors.textMuted }]}>{item.online ? '● Онлайн бичлэг' : '○ Офлайн бичлэг'}</Text></Card>)}</ScrollView></View>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, filters: { flexDirection: 'row', gap: 8, paddingHorizontal: 20, marginBottom: 12 }, filter: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18, backgroundColor: colors.surfaceAlt }, filterActive: { backgroundColor: colors.primary }, filterText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' }, filterTextActive: { color: colors.white }, content: { paddingHorizontal: 20, paddingBottom: 110 }, card: { marginBottom: 12 }, cardHeader: { flexDirection: 'row', justifyContent: 'space-between' }, date: { color: colors.text, fontSize: 16, fontWeight: '700' }, time: { color: colors.textMuted, fontSize: 12, marginTop: 4 }, score: { fontSize: 26, fontWeight: '800' }, divider: { height: 1, backgroundColor: colors.border, marginVertical: 14 }, metrics: { flexDirection: 'row' }, metric: { flex: 1 }, metricValue: { color: colors.text, fontSize: 14, fontWeight: '700' }, metricLabel: { color: colors.textMuted, fontSize: 9, marginTop: 3 }, online: { fontSize: 10, marginTop: 14 } });
