import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const SKILL_DIR = '/Users/nominganzorig/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const WORKSPACE = '/Users/nominganzorig/Desktop/intern-4ab-driver-fatigue';
const BUILD = path.join(WORKSPACE, '.pptx-build');
const { resolvePresentationFont } = await import(pathToFileURL(path.join(SKILL_DIR, 'container_tools/artifact_tool_utils.mjs')).href);
const font = resolvePresentationFont();
const P = { bg: '#08111F', navy: '#0E1C31', blue: '#3B82F6', cyan: '#66D9FF', green: '#46D38A', amber: '#F5B84B', red: '#FB6B6B', white: '#F5F8FC', muted: '#A9B7CA', line: '#29415F' };
const deck = Presentation.create({ slideSize: { width: 1280, height: 720 } });

function box(slide, x, y, w, h, fill = 'none', radius = 0, line = 'none') {
  return slide.shapes.add({ geometry: radius ? 'roundRect' : 'rect', position: { left: x, top: y, width: w, height: h }, fill, line: line === 'none' ? { fill: 'none', width: 0 } : { fill: line, width: 1 } });
}
function text(slide, value, x, y, w, h, opts = {}) {
  const s = box(slide, x, y, w, h, 'none');
  s.text = value;
  s.text.style = { typeface: font, fontSize: opts.size ?? 22, bold: opts.bold ?? false, color: opts.color ?? P.white, autoFit: 'shrinkText', align: opts.align ?? 'left', valign: opts.valign ?? 'top', breakLine: false };
  return s;
}
function title(slide, heading, sub) { text(slide, heading, 68, 48, 920, 52, { size: 34, bold: true }); if (sub) text(slide, sub, 70, 108, 840, 30, { size: 16, color: P.muted }); text(slide, 'FATIGUEGUARD', 1065, 54, 150, 24, { size: 11, bold: true, color: P.cyan, align: 'right' }); }
function footer(slide, n) { box(slide, 70, 676, 1140, 1, P.line); text(slide, `0${n}`, 70, 687, 45, 18, { size: 10, color: P.muted }); text(slide, 'Driver fatigue detection project', 930, 687, 280, 18, { size: 10, color: P.muted, align: 'right' }); }
function card(slide, x, y, w, h, heading, body, accent = P.blue) { box(slide, x, y, w, h, P.navy, 20, P.line); box(slide, x + 18, y + 20, 5, h - 40, accent, 4); text(slide, heading, x + 42, y + 23, w - 60, 30, { size: 19, bold: true }); text(slide, body, x + 42, y + 63, w - 65, h - 80, { size: 15, color: P.muted }); }
function note(slide, value) { slide.speakerNotes.textFrame.setText(value); }

// 1. Cover
{ const s = deck.slides.add(); s.background.fill = P.bg; const img = new Uint8Array(await fs.readFile(path.join(BUILD, 'fatigueguard-cover.png'))); s.images.add({ blob: img, contentType: 'image/png', alt: 'AI-generated night driving cover illustration', fit: 'cover', position: { left: 0, top: 0, width: 1280, height: 720 } }); box(s, 0, 0, 730, 720, { color: P.bg, transparency: 10 }); box(s, 0, 0, 1280, 720, { color: '#020713', transparency: 50 }); text(s, 'FATIGUE\nGUARD', 80, 112, 540, 160, { size: 64, bold: true }); text(s, 'Жолоочийн ядаргаа илрүүлэх ухаалаг систем', 84, 300, 500, 58, { size: 25, color: P.cyan }); text(s, 'Computer Vision + RAG + Mobile App', 84, 380, 420, 32, { size: 18, color: P.white }); box(s, 84, 470, 280, 2, P.blue); text(s, 'Багийн төслийн танилцуулга', 84, 494, 330, 26, { size: 15, color: P.muted }); note(s, 'Cover visual created with OpenAI image generation. It is an illustrative, non-documentary image.'); }

// 2. Problem
{ const s = deck.slides.add(); s.background.fill = P.bg; title(s, 'Асуудал', 'Урт зам, шөнийн жолоодлого болон өвлийн нөхцөл ядаргааны эрсдэлийг нэмэгдүүлдэг'); text(s, 'Ядарсан жолоочийн анхаарал, хариу үйлдэл, шийдвэр гаргалт сулардаг.', 70, 172, 810, 40, { size: 25, bold: true }); card(s, 70, 265, 330, 200, 'Нүд анилт', 'Нүд удаан хаагдах болон PERCLOS өсөх нь нойрмоглолын дохио болно.', P.cyan); card(s, 445, 265, 330, 200, 'Толгой дохих', 'Толгой давтамжтай доошлох нь анхаарал суларч байгааг илтгэнэ.', P.amber); card(s, 820, 265, 330, 200, 'Оройн цаг', 'Шөнийн урт замд жолооч ганцаараа, нэг хэвийн нөхцөлд удаан явдаг.', P.red); text(s, 'Зорилго: эрсдэлийн эхний шинжийг бодит цагт илрүүлж, аюулгүй зогсоож амрах шийдвэрт туслах.', 70, 530, 1030, 40, { size: 22, color: P.white }); footer(s, 2); note(s, 'Background: NHTSA notes drowsy driving can impair performance and is especially associated with nighttime and rural-road driving. Source: https://www.nhtsa.gov/risky-driving/drowsy-driving'); }

// 3. Solution
{ const s = deck.slides.add(); s.background.fill = P.bg; title(s, 'Шийдэл', 'Dashboard дээр байрлуулсан ухаалаг утас жолоочийн төлөвийг хянана'); text(s, 'Утасны урд камер', 92, 210, 190, 30, { size: 19, bold: true }); box(s, 95, 254, 170, 260, P.navy, 28, P.line); box(s, 114, 284, 132, 150, '#122B46', 16); text(s, '◉', 142, 310, 75, 70, { size: 56, color: P.cyan, align: 'center' }); text(s, 'front camera', 110, 455, 140, 25, { size: 14, color: P.muted, align: 'center' }); const steps = [['Нүд', 'Нүд нээлттэй эсэх, PERCLOS'], ['Толгой', 'Pitch өөрчлөлт, дохилтын давтамж'], ['Score', '0–100 эрсдэлийн үнэлгээ'], ['Alert', 'Дохиолол, vibration, зөвлөгөө']]; steps.forEach((it, i) => { const x = 360 + i * 205; box(s, x, 276, 170, 180, P.navy, 20, P.line); text(s, String(i + 1), x + 20, 300, 35, 28, { size: 16, bold: true, color: P.cyan }); text(s, it[0], x + 20, 346, 130, 30, { size: 21, bold: true }); text(s, it[1], x + 20, 390, 130, 48, { size: 13, color: P.muted }); if (i < 3) text(s, '›', x + 177, 340, 24, 40, { size: 32, color: P.blue, align: 'center' }); }); text(s, 'Камерын raw видео default байдлаар сервер рүү илгээхгүй. Хувийн мэдээллийг төхөөрөмж дээр боловсруулах зарчим баримтална.', 360, 520, 800, 42, { size: 17, color: P.muted }); footer(s, 3); note(s, 'System design based on the project specification.'); }

// 4. Architecture
{ const s = deck.slides.add(); s.background.fill = P.bg; title(s, 'Системийн архитектур', 'Real-time detection ба аюулгүй ажиллагааны зөвлөгөөг тусгаарласан урсгал'); const layers = [['Mobile app', 'CameraView, setup, calibration, driving UI', P.cyan], ['Computer Vision', 'Face landmarks, нүд анилт, толгойн өнцөг', P.blue], ['Fatigue engine', 'PERCLOS, nods, score, risk level', P.amber], ['Safety response', 'Siren, vibration, source-grounded advice', P.red]]; layers.forEach((it, i) => { const y = 172 + i * 105; box(s, 120, y, 1040, 76, P.navy, 18, P.line); box(s, 120, y, 12, 76, it[2], 18); text(s, it[0], 165, y + 17, 265, 28, { size: 20, bold: true }); text(s, it[1], 470, y + 19, 600, 28, { size: 17, color: P.muted }); if (i < 3) text(s, '↓', 613, y + 79, 50, 26, { size: 20, color: P.blue, align: 'center' }); }); text(s, 'RAG нь сэрэмжлүүлгийн үндсэн шийдвэрийг гаргахгүй. Эрсдэлийн ангилал тогтсоны дараа баталгаатай эх сурвалжаас зөвлөгөө сонгоно.', 120, 610, 1020, 35, { size: 17, color: P.white }); footer(s, 4); note(s, 'Architecture reflects project design. RAG safety constraint is a design decision.'); }

// 5. App flow
{ const s = deck.slides.add(); s.background.fill = P.bg; title(s, 'Mobile app flow', 'FatigueGuard UI нь жолоочийг камераа тохируулж, калибрац хийсний дараа monitoring screen рүү оруулна'); const screens = [['1', 'Нүүр хуудас', 'Жолоодлого эхлүүлэх'], ['2', 'Camera setup', 'Нүүр, гэрэл, байрлал'], ['3', 'Калибраци', 'Нүд ба толгойн baseline'], ['4', 'Driving', 'Score ба сэрэмжлүүлэг'], ['5', 'Summary', 'Сессийн дүн ба AI зөвлөгөө']]; screens.forEach((it, i) => { const x = 70 + i * 235; box(s, x, 215, 185, 250, '#0D1B2E', 28, P.line); text(s, it[0], x + 20, 235, 42, 32, { size: 20, bold: true, color: P.cyan }); text(s, it[1], x + 20, 292, 145, 30, { size: 18, bold: true }); text(s, it[2], x + 20, 338, 145, 56, { size: 14, color: P.muted }); if (i < 4) text(s, '›', x + 187, 318, 38, 40, { size: 32, color: P.blue, align: 'center' }); }); text(s, 'History, Settings, offline-data toggle болон alert volume control нь bottom navigation-аас ашиглагдана.', 70, 535, 1050, 34, { size: 19, color: P.white }); footer(s, 5); note(s, 'Based on the FatigueGuard UI imported into the Expo project.'); }

// 6. Current status
{ const s = deck.slides.add(); s.background.fill = P.bg; title(s, 'Одоогийн хэрэгжилтийн төлөв', 'UI prototype болон Computer Vision модулийг ялгаж ойлгох нь чухал'); card(s, 80, 185, 500, 310, 'Бэлэн болсон хэсэг', '• Expo mobile UI\n• Камерын preview ба permission\n• Setup, calibration, monitoring flow\n• History, settings, summary screens\n• Alert-ийн UI болон debug panel', P.green); card(s, 700, 185, 500, 310, 'Дараагийн хэрэгжүүлэх хэсэг', '• Face landmark detector\n• Нүүр camera frame дотор байгаа эсэх\n• Нүд анилт ба head-nod хэмжилт\n• Fatigue Score-ийн бодит өгөгдөл\n• Native siren болон RAG API integration', P.amber); text(s, 'Чухал: одоогийн Camera setup нь камераас нүүрний landmark уншдаггүй. Нөхцөл шалгалт нь UI/debug state дээр ажиллаж байна.', 80, 555, 1110, 45, { size: 20, bold: true, color: P.amber }); footer(s, 6); note(s, 'Implementation status verified from the target Expo project source on 2026-09-17.'); }

// 7. Fatigue logic
{ const s = deck.slides.add(); s.background.fill = P.bg; title(s, 'Fatigue Score-ийн логик', 'Эхний prototype босго нь calibration болон бодит туршилтаар сайжирна'); const metrics = [['PERCLOS', 'Сүүлийн 60 секундэд нүд анисан кадрын хувь', '45%'], ['Long closure', 'Нүд 0.8 секундээс удаан хаагдах', '30%'], ['Head nod', '60 секундэд давтагдсан толгой дохилт', '25%']]; metrics.forEach((m, i) => { const y = 180 + i * 100; text(s, m[0], 100, y, 200, 28, { size: 20, bold: true, color: [P.cyan, P.amber, P.red][i] }); text(s, m[1], 330, y, 550, 30, { size: 16, color: P.muted }); text(s, m[2], 1010, y, 100, 28, { size: 20, bold: true, color: P.white, align: 'right' }); box(s, 100, y + 47, 1000, 8, P.line, 4); box(s, 100, y + 47, [450, 300, 250][i], 8, [P.cyan, P.amber, P.red][i], 4); }); text(s, '40–64  Анхаарах', 150, 530, 230, 30, { size: 19, color: P.amber }); text(s, '65–79  Дуут сэрэмжлүүлэг', 480, 530, 300, 30, { size: 19, color: P.red }); text(s, '80–100  Аюулгүй зогсож амрах', 850, 530, 330, 30, { size: 19, color: P.red }); text(s, 'Нэг дохиогоор шийдвэр гаргахгүй. Хөдөлгөөнт цонх, smoothing, cooldown ашиглан false alarm-ыг бууруулна.', 100, 607, 1000, 30, { size: 17, color: P.white }); footer(s, 7); note(s, 'Thresholds are proposed prototype parameters, not validated medical thresholds.'); }

// 8. Demo and roadmap
{ const s = deck.slides.add(); s.background.fill = P.bg; title(s, 'Demo ба дараагийн алхам', 'Танилцуулгын demo нь UI flow-г харуулж, CV integration-ийн шаардлагыг тодорхой тайлбарлана'); const items = [['Demo', 'Home → Camera setup → Calibration → Driving', P.cyan], ['Туршилт', 'Гэрэлтүүлэг, утасны байрлал, нүүрний өнцөг', P.amber], ['Integration', 'Face detector, score engine, siren, RAG', P.blue], ['Validation', 'False alarm болон missed detection-ийг бодит жолоодлогын нөхцөлд хэмжих', P.green]]; items.forEach((it, i) => { const y = 170 + i * 105; text(s, `${i + 1}`, 95, y + 6, 40, 30, { size: 22, bold: true, color: it[2] }); text(s, it[0], 175, y, 250, 28, { size: 20, bold: true }); text(s, it[1], 460, y + 2, 630, 48, { size: 17, color: P.muted }); box(s, 95, y + 68, 995, 1, P.line); }); text(s, 'Асуулт, санал', 70, 628, 420, 42, { size: 32, bold: true, color: P.cyan }); text(s, 'Баярлалаа', 975, 636, 230, 26, { size: 18, color: P.muted, align: 'right' }); footer(s, 8); note(s, 'Project roadmap and presentation close.'); }

const candidate = path.join(WORKSPACE, '.codex-finalizer', 'fatigueguard-project-presentation-candidate.pptx');
await (await PresentationFile.exportPptx(deck)).save(candidate);
console.log(candidate);
